[local]
localhost

[mongodb]
mongodb.daws90.fun

[redis]
redis.daws90.fun

[mysql]
mysql.daws90.fun

[rabbitmq]
rabbitmq.daws90.fun

[catalogue]
catalogue.daws90.fun

[cart]
cart.daws90.fun

[user]
user.daws90.fun

[shipping]
shipping.daws90.fun

[payments]
payments.daws90.fun

[frontend]
frontend.daws90.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb.daws90.fun
REDIS_HOST=redis.daws90.fun
MYSQL_HOST=mysql.daws90.fun
RABBITMQ_HOST=rabbitmq.daws90.fun
CATALOGUE_HOST=catalogue.daws90.fun
USER_HOST=user.daws90.fun
CART_HOST=cart.daws90.fun
SHIPPING_HOST=shipping.daws90.fun
PAYMENTS_HOST=payments.daws90.fun
FRONTEND_HOST=frontend.daws90.fun