- name: app setup
  import_role:
    name: common
    tasks_from: appsetup

- name: python installation
  import_role: 
    name: common
    tasks_from: python

- name: systemd setup
  import_role:
    name: common
    tasks_from: systemd-setup

- name: restart and enable
  import_role:
    name: common
    tasks_from: enablerestart
    